#+TITLE: Primer Concepto -Análisis del estado de las bandas musicales en la escena colombiana
#+AUTHOR:Rodrigo Castillo, Alejandra Campo, Gran Maestro Chamán.


* Qué base de datos escogieron.
La idea de este proyecto es hacer un análisis del estado de las bandas musicales
en la escena musical colombiana, sin embargo, aunque existen muchas bases de
datos y formas diversas
de recolectar datos sobre música, no existe un dataset sólido sobre la música en
Colombia que cuente con suficientes features para aplicar análisis estadístico
de datos en ellos. La mayoría de las plataformas (como spotify) que cuentan con
una API no dan información sobre la región en donde se encuenta un artista.

Sin embargo, no tiene gracia hacer análisis de datos sobre grandes datasets que
no tienen influencia sobre los miembros del grupo y sobre los cuales ya existen
análisis muy complejos hechos por gente mas experimentada, por lo que el grupo
se dispuso a hacer su propio dataframe de la música en Colombia.

** Metodología de la recolección de datos sobre bandas en la escena colombiana
*** SIMUS
Existen diversos datos sobre bandas colombianas , por ejemplo existe una entidad que se llama el SIMUS en el cuál las bandas musicales que tienen contrataciones tienen que registratse legalmente, esta base de datos cuenta con 882 bandas que se han registrado legalmente.
#+begin_src python :results output :exports both :session simus
import pandas as pd
datos_simus = pd.read_excel("bandas_simus.xls")
print(datos_simus.head(10))
print(datos_simus.shape)
#+end_src

#+RESULTS:
#+begin_example
                                            Nombre                        Tipo Agrupacion      Pais  Departamento       Municipio     Estado
0  Ensamble musical casa de la cultura San Alberto                               Conjunto  COLOMBIA         CESAR     SAN ALBERTO  Publicado
1                 Charlie Rueda & The Jazzmorgans   Agrupaciones de Música Popular Urbana  COLOMBIA     SANTANDER     BUCARAMANGA  Publicado
2                                   Gente pescaito                               Conjunto  COLOMBIA  BOGOTÁ, D.C.    BOGOTÁ, D.C.  Publicado
3                                        los Andes                               Conjunto  COLOMBIA         HUILA         GIGANTE  Publicado
4                       CORO MUNICIPAL DE  MALAMBO                                   Coro  COLOMBIA     ATLÁNTICO         MALAMBO  Publicado
5                                       CORO ATRES                                   Coro  COLOMBIA        NARIÑO         IPIALES  Publicado
6                                      A TRES TRIO                                   Trio  COLOMBIA        NARIÑO         IPIALES  Publicado
7                    CUERPO Y ALMA LATIN ROCK BAND  Agrupaciones de Música Popular Urbana  COLOMBIA         HUILA     SANTA MARÍA  Publicado
8                        banda escuela 16 de julio                                  Banda  COLOMBIA       BOLÍVAR  SAN ESTANISLAO  Publicado
9       gaita casa de la cultura de san estanislao     Agrupaciones de Música Tradicional  COLOMBIA       BOLÍVAR  SAN ESTANISLAO  Publicado
(882, 6)
#+end_example

En esta base de datos cuenta con las columnas:
- nombre de la banda
- tipo de agrupación
- país(todas son colombianas)
- Departamento del país
- Municipio
- Estado de la banda
*** BOMM (Bogotá Music Market)
Existe una revista llamada BOMM es una plataforma de promoción y circulación organizada por la Cámara de Comercio de Bogotá, como parte de su programa de apoyo a las Industrias Creativas y Culturales, en esta página existe un catálogo de las bandas que han participado en eventos en el año 2021 (https://www.bogotamusicmarket.com/Artistas?year=2021) (no existen mas años y este input es vulnerable a RCE injection por si alguien quiere decirle a los de BOMM).
En BOMM no existe propiamente un Dataset, sin embargo, están todas los artistas inscritos, por lo que se puede hacer un simple programa que los scrapee:
#+begin_src python :results output :exports both :session simus
from selenium import webdriver
import pandas as pd
from time import sleep
#crea una session de un driver de google chrome
driver = webdriver.Chrome()
bomm_artist_url = "https://www.bogotamusicmarket.com/Artistas?year=2021"
driver.get(bomm_artist_url)
#espera 1 segundo para que el driver seguro cargue la página
sleep(1)
not_done = True
bomm_list = []
while(not_done):
    #agarro todos los nombres de una pagina específica
    for i in range(1,17):
        #si no se puede agarrar el elemento es porque no hay mas bandas
        try:
            first_artist = driver.find_element_by_xpath(f"/html/body/div[1]/div/div/div/div[2]/div/div[{i}]/figure/figcaption/h4/a")
            name = first_artist.text
            data = {"band_name":name}
            bomm_list.append(data)
        except:
            not_done = False
            print("done")
            break
    try:
        #voy a la siguiente pagina, y hago esto hasta que no haya mas artistas
        next_button = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/div[3]/div[3]/div/a")
        next_button.click()
        sleep(1)
    except:
        driver.close()

bomm_data = pd.DataFrame(bomm_list)
print(bomm_data)
print(bomm_data.shape())
#+end_src

#+RESULTS:
#+begin_example
done
              band_name
0    8bm - 8bits Memory
1         Ácido Pantera
2          Afro Legends
3    Agrupación Guarura
4             Aka Rezzo
..                  ...
252               Yooko
253               Zafat
254         Zalama Crew
255           Zatélithe
256              Zultan

[257 rows x 1 columns]
#+end_example

*** Bandas de circulart:
Así como existe Bomm en Bogotá, existe Circulart en Medellín, acá adjunto el script que scrappea los datos de circulart
#+begin_src python :results output :exports both :session simus
from selenium import webdriver
import pandas as pd
from time import sleep

link = "https://circulart.org/2021/artistas-rueda/"
driver = webdriver.Chrome()
driver.get(link)


not_error = True
index = 1
ids = []
while(not_error):
    try:
        artist_id = driver.find_element_by_xpath(f"/html/body/div[1]/div/div/div/article/div/div/div/div[2]/div/div/div/div/div/div[{index}]").get_attribute("id")
        index+=1
        ids.append(artist_id)
    except:
        not_error = False

print(len(ids))
total_info  = []
for i in ids:
    artist_url = f"https://circulart.org/2021/portafolio-artista-rueda/?p={i}"
    driver.get(artist_url)
    driver.implicitly_wait(1)
    artist_name = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/article/div/div/div/div[2]/div/div[1]/div/div/div/h1").text
    artist_description = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/article/div/div/div/div[2]/div/div[1]/div/div/div/div[2]").text
    artist_gen = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/article/div/div/div/div[2]/div/div[1]/div/div/div/div[3]").text
    info = {"name":artist_name,
                  "artist_description":artist_description,
                  "generos":artist_gen,
                  "id_circulart":i}
    total_info.append(info)

circulart_data = pd.DataFrame(total_info)
driver.close()
print(circulart_data)
#+end_src
*** Bandas o cantantes famosos
Con el fin del proyecto, una de las cosas que se busca analizar es que factores hacen que una banda sea famosa y que otra no , por lo que también añadiré una lista de cantantes muy famosos colombianos al dataset también scrapeado de https://www.ranker.com/list/bands-from-colombia/reference

*nota:el script que scrapeo estos datos está en el repositorio pero no se puede llamar desde el notebook pues es un poco mañoso*

#+begin_src python :results output :exports both :session simus
import json
import pandas as pd
with open("famous_data.json") as file:
    data = json.load(file)
famous_dataframe = pd.DataFrame(data)
print(famous_dataframe)
#+end_src

#+RESULTS:
#+begin_example
                      name
0                  Shakira
1                   Juanes
2            Mateo Camargo
3        Alfredo Gutierrez
4            Alex González
..                     ...
100     Gabriel Torregrosa
101       Rafael Rodríguez
102         Fredys Arrieta
103      Alejandro Palacio
104  David Escobar Gallego

[105 rows x 1 columns]
#+end_example

*** Sin embargo, lo que se pretende con estos datos es extraer solamente los nombres de las bandas activas en la escena colombiana, pues, posteriormente, a partir de estas bandas se obtendrá la información de spotify, por lo que unificaré los datos.

#+begin_src python :results output :exports both :session simus
import pandas as pd

colombia_scene_list = []
#añado los datos del dataframe que hice de famosos previamente
for i in famous_dataframe["name"]:
    data = {"name":i,
            "lugar_extraido":"pagina_artistas_famosos"}
    colombia_scene_list.append(data)

#añado los datos de circulart
for i in circulart_data["name"]:
    data = {"name":i,
            "lugar_extraido":"circulart"}
    colombia_scene_list.append(data)
#añado los datos del dataframe que hice de BOMM previamente
for i in bomm_data["band_name"]:
    data = {"name":i,
            "lugar_extraido":"bomm"}
    colombia_scene_list.append(data)

#añado los datos que descargue del SIMUS
for i in datos_simus["Nombre"]:
    data = {"name":i,
            "lugar_extraido":"simus"}
    colombia_scene_list.append(data)

colombia_state_names = pd.DataFrame(colombia_scene_list)
#
#guardo los datos para vincularlos posteriormente con spotify y con youtube
colombia_state_names.to_csv("nombres_bandas_generados.csv")
print(colombia_state_names.tail(5))
#+end_src

#+RESULTS:
:                                                    name lugar_extraido
: 1239  Semillero escuela Municipal de música de Piendamó          simus
: 1240                   Chirimia del Pacifico Colombiano          simus
: 1241            ESCUELA DE FORMACION MUSICAL PAEZ VIVE           simus
: 1242                                   Pal' Lereo Pabla          simus
: 1243                                       Mar a fuera           simus

** Merge con Spotify:
*** Concepto
Spotify cuenta con una API bastante completa que suministra mucha información
sobre las bandas que se encuentran en esta plataforma. Ya que se tiene un
dataset con muchos nombres de bandas que suenan en la escena de
la música colombiana, ahora lo que busco es enriquecer los datos que tengo
buscando los nombres de las bandas en spotify y extrayendo sus features. En un
proyecto anterior, junto con Juan Pablo, habíamos hecho una clase que funcionaba
dentro de la API de spotify para relacionar nombres de artistas con sus
respectivos ids en spotify

*** Proceso de enriquecer los datos:
previamente se almacenaron los datos en "nombres_bandas_generados.csv" , lo que
busco es asociar a cada artista con su respectivo id de spotify con el fin de
luego poder extraer la información correspondiente a este

*fue muy pesado el script que hacía el merge por lo que me tocó correrlo como un script aparte que está en el repositorio pero no se puede correr desde el documento*, de todas formas, los datos sobre los que se va a trabajar el proyecto son estos (aunque luego se podrían adjuntar matrices respectivas a las músicas de cada artista de ser pertinente)
#+begin_src python :results output :exports both :session simus
import pandas as pd
final_data = pd.read_csv("final_data.csv")
print(final_data.head(4))
print(final_data.columns)
print(final_data.shape)
#+end_src

#+RESULTS:
#+begin_example
   Unnamed: 0      name_scrapped                      id                                       link_spotify  followers  ... popularidad  nombre_en_spotify  type_of_artist           lugar_extraido index_on_last_dataset
0           0            Shakira  <built-in function id>  https://open.spotify.com/artist/0EmeFodog0BfCg...   22483270  ...          85            Shakira  <class 'type'>  pagina_artistas_famosos                     1
1           1             Juanes  <built-in function id>  https://open.spotify.com/artist/0UWZUmn7sybxMC...    3438332  ...          77             Juanes  <class 'type'>  pagina_artistas_famosos                     2
2           2      Mateo Camargo  <built-in function id>                                    not in database          0  ...           0    not in database  <class 'type'>  pagina_artistas_famosos                     3
3           3  Alfredo Gutierrez  <built-in function id>  https://open.spotify.com/artist/7esYnrPzQX1JWW...      77452  ...          47  Alfredo Gutierrez  <class 'type'>  pagina_artistas_famosos                     4

[4 rows x 12 columns]
Index(['Unnamed: 0', 'name_scrapped', 'id', 'link_spotify', 'followers',
       'generos', 'imagenes', 'popularidad', 'nombre_en_spotify',
       'type_of_artist', 'lugar_extraido', 'index_on_last_dataset'],
      dtype='object')
(1244, 12)
#+end_example

* Razón por la cuál elegimos esta base de datos:
** 1
porque junto con Juan Pablo nos divertimos haciendo proyectos relacionados con música ya que siempre descubrimos bandas excelentes. Además, porque tiene sentido estudiar la música que consumimos.
** 2
porque el hecho de que no existan datasets sobre el tema implica que es un tema que nadie ha estudiado con rigurosidad, y este análisis le puede servir a promotores de la industria musical o a bandas de amigos que quieran tomar estrategias para aumentar su popularidad.
** 3
porque este proyecto puede revelar un panorama muy interesante de la música en Colombia

* Qué métodos pueden potencialmente aplicarse con dicha base de datos.
** Respecto a la comparación:
Se pueden usar métodos de comparación para ver que factores influyen en la popularidad de un artista en Colombia
** Respecto a la clasificación:
Se puede intentar aplicar métodos de regresiones logísticas para saber si un artista, según sus features, va a ser popular o no
** Respecto al clustering:
Se puede aplicar modelos de clustering como Kmeans para entender que tipos de bandas suenan en nuestro país
** Respecto a la reducción de dimensionalidad:
Se puede reducir la dimensión de las matrices de los mel-espectrogramas de
canciones de los artistas para poder visualizar en un plano un panorama completo de la música
colombiana (que en realidad es mi meta personal con este proyecto.) , con esto,
tener una visión mas clara de como se mueve la onda musical en Bogotá.
